instance_name= "sidharth-test"
region= "us-central1"
project_id= "angelic-hexagon-307814"
container_name = "demo"
container_port = 8080
container_image = "us-docker.pkg.dev/cloudrun/container/hello"
container_cpu = "2000m"
container_memory = "1Gi"
container_timeout_seconds = 360
cloud_run_service_account = "svc-terraform@angelic-hexagon-307814.iam.gserviceaccount.com"
container_concurrency = 200